#!/bin/bash
set -eu -o pipefail

cd "$(dirname "$0")"

if ! command -v bashly &> /dev/null; then
	shopt -s expand_aliases
	alias bashly='docker run --rm -u $(id -u ${USER}):$(id -g ${USER}) --volume "$PWD:/app" dannyben/bashly'
fi

(
	cat src/initialize.sh
	echo '#:'
	echo '#: commands:'
	for cmd in src/*_command.sh; do
		echo '#: -'
		sed 's%^#:%#:  %' "$cmd"
	done
) | grep -E '^#:' | sed 's%^#: \?%%' \
> src/bashly.yml

bashly generate --quiet

exec ./git-draft "$@"
