#!/bin/bash
set -eu -o pipefail

cd "$(dirname "$0")"

shellcheck --shell=bash --external-sources ./run ./test src/**/*.sh tests/test_lib tests/*.sh

./run --help > /dev/null # Regenerate script

for test in tests/**/*.sh; do
	if ! bash "$test" &>"${test/.sh/.out}"; then
		echo "Failure in $test:"
		cat "${test/.sh/.out}"
		exit 1
	fi
	if ! cmp "${test/.sh/.txt}" "${test/.sh/.out}"; then
		diff --unified "${test/.sh/.txt}" "${test/.sh/.out}"
		exit 1
	fi
done

echo All tests passed!
