#!/bin/bash
set -eu -o pipefail

cd "$(dirname "$0")"

./run --help > /dev/null # Regenerate script

# TODO work out what SC2030/SC2031 is complaining about and fix it
shellcheck -e SC2030,SC2031 --shell=bash --external-sources ./run ./test ./git-draft tests/test_lib tests/{,**}/*.sh

for test in tests/*.sh tests/**/*.sh; do
	if ! bash "$test" &>"${test/.sh/.out}"; then
		echo "Failure in $test:"
		cat "${test/.sh/.out}"
		exit 1
	fi
	if [[ ! -e "${test/.sh/.txt}" ]]; then
		touch "${test/.sh/.txt}"
	fi
	if cmp "${test/.sh/.txt}" "${test/.sh/.out}"; then
		rm "${test/.sh/.out}"
	else
		diff --unified "${test/.sh/.txt}" "${test/.sh/.out}" || true
		read -r -N1 -p "[a]ccept changes, or [f]ail test? " accept
		echo
		if [[ "$accept" == 'a' ]]; then
			cp "${test/.sh/.out}" "${test/.sh/.txt}"
			echo "Updated expected output for $test"
		else
			echo "Rejected changes to output for $test"
			exit 1
		fi
	fi
done

echo All tests passed!
