#!/bin/bash
#
# Utilities for tests.
# 
# This file should be `source`d by each test.

set -eu -o pipefail

# Put our git-draft at the front of the path
PATH="$(realpath "$(dirname "${BASH_SOURCE[0]}")/../"):$PATH"

test_init() {
	# Fix these in place so commit hashes don't change
	export GIT_AUTHOR_NAME=test
	export GIT_AUTHOR_EMAIL=test@test
	export GIT_AUTHOR_DATE="1/1/1970 0:00 +0000"
	export GIT_COMMITTER_NAME=test
	export GIT_COMMITTER_EMAIL=test@test
	export GIT_COMMITTER_DATE="1/1/1970 0:00 +0000"
	
	tmpdir="$(mktemp --tmpdir --directory git-draft-test.XXXXXXXXXX)"
	function finish {
		set +x
		rm -rf "$tmpdir"
	}
	trap finish EXIT
	
	cd "$tmpdir"
	
	set -x
}

test_init_git() {
	git init --quiet
	git switch --quiet -c main
}

test_init_git_fixture() {
	(
		set +x
		test_init_git
		echo 'A' > a.txt
		git add -A
		git commit -m 'Add A'
		echo 'B' > b.txt
		git add -A
		git commit -m 'Add B'
	) > /dev/null
}
