#!/usr/bin/env bash

# git-draft: stash, don't stage!
# https://github.com/wolfgang42/git-draft/

# This script was generated by bashly (https://github.com/DannyBen/bashly)
# Modifying it manually is not recommended

# :script.bash3_bouncer
if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
  printf "bash version 4 or higher is required\n"
  exit 1
fi
