name: CI

# TODO I'm not entirely convinced this is the right set of events
on: [workflow_dispatch, push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - run: DOCKERIZED_SHELLCHECK=1 GIT_DRAFT_WITHOUT_TTY=1 ./test

      - name: Upload script as artifact
        uses: actions/upload-artifact@v2
        with:
          name: git-draft.zip
          path: git-draft
